2023-03-17 23:13:43,881 INFO    MainThread:9732 [wandb_setup.py:_flush():68] Configure stats pid to 9732
2023-03-17 23:13:43,881 INFO    MainThread:9732 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Shivam Maurya\.config\wandb\settings
2023-03-17 23:13:43,881 INFO    MainThread:9732 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Shivam Maurya\OneDrive\Desktop\IIT_MADRAS\Deep Learning\assignment 1\CS6910-Deep_Learning_Assignment-1\wandb\settings
2023-03-17 23:13:43,882 INFO    MainThread:9732 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-17 23:13:43,882 INFO    MainThread:9732 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-17 23:13:43,884 INFO    MainThread:9732 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\Shivam Maurya\OneDrive\Desktop\IIT_MADRAS\Deep Learning\assignment 1\CS6910-Deep_Learning_Assignment-1\wandb\run-20230317_231343-43yfe3fr\logs\debug.log
2023-03-17 23:13:43,885 INFO    MainThread:9732 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\Shivam Maurya\OneDrive\Desktop\IIT_MADRAS\Deep Learning\assignment 1\CS6910-Deep_Learning_Assignment-1\wandb\run-20230317_231343-43yfe3fr\logs\debug-internal.log
2023-03-17 23:13:43,885 INFO    MainThread:9732 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000230266B06A0>
2023-03-17 23:13:43,886 INFO    MainThread:9732 [wandb_init.py:init():532] calling init triggers
2023-03-17 23:13:43,887 INFO    MainThread:9732 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-17 23:13:43,887 INFO    MainThread:9732 [wandb_init.py:init():588] starting backend
2023-03-17 23:13:43,888 INFO    MainThread:9732 [wandb_init.py:init():592] setting up manager
2023-03-17 23:13:43,900 INFO    MainThread:9732 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-17 23:13:43,911 INFO    MainThread:9732 [wandb_init.py:init():599] backend started and connected
2023-03-17 23:13:43,945 INFO    MainThread:9732 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-17 23:13:43,951 INFO    MainThread:9732 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-17 23:13:43,951 INFO    MainThread:9732 [wandb_init.py:init():687] updated telemetry
2023-03-17 23:13:44,088 INFO    MainThread:9732 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-17 23:13:44,858 INFO    MainThread:9732 [wandb_run.py:_on_init():2134] communicating current version
2023-03-17 23:13:45,276 INFO    MainThread:9732 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.14.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-17 23:13:45,276 INFO    MainThread:9732 [wandb_init.py:init():775] starting run threads in backend
2023-03-17 23:14:00,660 WARNING MainThread:9732 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Anaconda\lib\site-packages\wandb\sdk\wandb_init.py", line 787, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "C:\Anaconda\lib\site-packages\wandb\sdk\lib\mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Anaconda\lib\site-packages\wandb\sdk\lib\mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Anaconda\lib\site-packages\wandb\sdk\lib\mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Anaconda\lib\threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Anaconda\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-03-17 23:14:06,605 WARNING MsgRouterThr:9732 [router.py:message_loop():77] message_loop has been closed
